item:
  type: diamond sword
  amount: 1
  name: custom name
  lore:
    - monkey
    - mono
  custom-model: 10001
  damage: 100
  repair-cost: 100
  flags:
    - hide enchants
  unbreakable: false
  enchants:
    sharpness: 5
  attributes:
    - type: generic.attack_damage
      name: Attack Damage Modifier
      amount: 2.0
      slot: mainhand
      operation: 0

location:
  world: world
  x: 100
  y: 100
  z: 100
  yaw: 10
  pitch: 10

locations:
  - {world: world, x: 100, y: 100, z: 100, yaw: 10, pitch: 10}
  - {x: 100, y: 100, z: 100, yaw: 10, pitch: 10}
  - {world: world, x: 100, y: 100, z: 100}
  - {x: 100, y: 100, z: 100}

split-string: 'monkey:1:true'